source "https://rubygems.org"

gem "jekyll", "~> 4.4.0"

gem "minima", "~> 2.5"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-paginate"
  gem 'jekyll-tagging'
  gem 'jekyll-archives'
end
